//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace seamless_loop_music.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("seamless_loop_music.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to AppTitle.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to LoopStartLabel.
        /// </summary>
        public static string LoopStartLabel {
            get {
                return ResourceManager.GetString("LoopStartLabel", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to LoopEndLabel.
        /// </summary>
        public static string LoopEndLabel {
            get {
                return ResourceManager.GetString("LoopEndLabel", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MatchWindowTitle.
        /// </summary>
        public static string MatchWindowTitle {
            get {
                return ResourceManager.GetString("MatchWindowTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to SearchRadiusTitle.
        /// </summary>
        public static string SearchRadiusTitle {
            get {
                return ResourceManager.GetString("SearchRadiusTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to FilePathTitle.
        /// </summary>
        public static string FilePathTitle {
            get {
                return ResourceManager.GetString("FilePathTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ApplyAndTest.
        /// </summary>
        public static string ApplyAndTest {
            get {
                return ResourceManager.GetString("ApplyAndTest", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ButtonApply.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MyPlaylist.
        /// </summary>
        public static string MyPlaylist {
            get {
                return ResourceManager.GetString("MyPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ToolTipAddPlaylist.
        /// </summary>
        public static string ToolTipAddPlaylist {
            get {
                return ResourceManager.GetString("ToolTipAddPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuRefresh.
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuRename.
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuDeletePlaylist.
        /// </summary>
        public static string MenuDeletePlaylist {
            get {
                return ResourceManager.GetString("MenuDeletePlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuNewPlaylist.
        /// </summary>
        public static string MenuNewPlaylist {
            get {
                return ResourceManager.GetString("MenuNewPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to FeatureLoop.
        /// </summary>
        public static string FeatureLoop {
            get {
                return ResourceManager.GetString("FeatureLoop", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to FeatureLoopToolTip.
        /// </summary>
        public static string FeatureLoopToolTip {
            get {
                return ResourceManager.GetString("FeatureLoopToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ResetAB.
        /// </summary>
        public static string ResetAB {
            get {
                return ResourceManager.GetString("ResetAB", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ResetABToolTip.
        /// </summary>
        public static string ResetABToolTip {
            get {
                return ResourceManager.GetString("ResetABToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PlayModeToolTip.
        /// </summary>
        public static string PlayModeToolTip {
            get {
                return ResourceManager.GetString("PlayModeToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MatchStartToolTip.
        /// </summary>
        public static string MatchStartToolTip {
            get {
                return ResourceManager.GetString("MatchStartToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MatchEndToolTip.
        /// </summary>
        public static string MatchEndToolTip {
            get {
                return ResourceManager.GetString("MatchEndToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PyRanking.
        /// </summary>
        public static string PyRanking {
            get {
                return ResourceManager.GetString("PyRanking", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PyRankingToolTip.
        /// </summary>
        public static string PyRankingToolTip {
            get {
                return ResourceManager.GetString("PyRankingToolTip", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MatchStart.
        /// </summary>
        public static string MatchStart {
            get {
                return ResourceManager.GetString("MatchStart", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MatchEnd.
        /// </summary>
        public static string MatchEnd {
            get {
                return ResourceManager.GetString("MatchEnd", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TitleLoopCandidates.
        /// </summary>
        public static string TitleLoopCandidates {
            get {
                return ResourceManager.GetString("TitleLoopCandidates", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PromptSelectLoop.
        /// </summary>
        public static string PromptSelectLoop {
            get {
                return ResourceManager.GetString("PromptSelectLoop", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderScore.
        /// </summary>
        public static string HeaderScore {
            get {
                return ResourceManager.GetString("HeaderScore", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderStart.
        /// </summary>
        public static string HeaderStart {
            get {
                return ResourceManager.GetString("HeaderStart", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderEnd.
        /// </summary>
        public static string HeaderEnd {
            get {
                return ResourceManager.GetString("HeaderEnd", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderDuration.
        /// </summary>
        public static string HeaderDuration {
            get {
                return ResourceManager.GetString("HeaderDuration", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderNoteDistance.
        /// </summary>
        public static string HeaderNoteDistance {
            get {
                return ResourceManager.GetString("HeaderNoteDistance", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ButtonUpdate.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ButtonClose.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to SettingsTitle.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MusicFoldersHeader.
        /// </summary>
        public static string MusicFoldersHeader {
            get {
                return ResourceManager.GetString("MusicFoldersHeader", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MusicFoldersSub.
        /// </summary>
        public static string MusicFoldersSub {
            get {
                return ResourceManager.GetString("MusicFoldersSub", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnAddFolder.
        /// </summary>
        public static string BtnAddFolder {
            get {
                return ResourceManager.GetString("BtnAddFolder", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnRemove.
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnScan.
        /// </summary>
        public static string BtnScan {
            get {
                return ResourceManager.GetString("BtnScan", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnScanning.
        /// </summary>
        public static string BtnScanning {
            get {
                return ResourceManager.GetString("BtnScanning", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DataManagementHeader.
        /// </summary>
        public static string DataManagementHeader {
            get {
                return ResourceManager.GetString("DataManagementHeader", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DataManagementSub.
        /// </summary>
        public static string DataManagementSub {
            get {
                return ResourceManager.GetString("DataManagementSub", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnSync.
        /// </summary>
        public static string BtnSync {
            get {
                return ResourceManager.GetString("BtnSync", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnSyncing.
        /// </summary>
        public static string BtnSyncing {
            get {
                return ResourceManager.GetString("BtnSyncing", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to LanguageHeader.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to LanguageSub.
        /// </summary>
        public static string LanguageSub {
            get {
                return ResourceManager.GetString("LanguageSub", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgScanCompleted.
        /// </summary>
        public static string MsgScanCompleted {
            get {
                return ResourceManager.GetString("MsgScanCompleted", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgSyncSuccess.
        /// </summary>
        public static string MsgSyncSuccess {
            get {
                return ResourceManager.GetString("MsgSyncSuccess", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to NavAlbum.
        /// </summary>
        public static string NavAlbum {
            get {
                return ResourceManager.GetString("NavAlbum", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to NavArtist.
        /// </summary>
        public static string NavArtist {
            get {
                return ResourceManager.GetString("NavArtist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to NavPlaylist.
        /// </summary>
        public static string NavPlaylist {
            get {
                return ResourceManager.GetString("NavPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to NavFolder.
        /// </summary>
        public static string NavFolder {
            get {
                return ResourceManager.GetString("NavFolder", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PlaylistAll.
        /// </summary>
        public static string PlaylistAll {
            get {
                return ResourceManager.GetString("PlaylistAll", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PlaylistFavorites.
        /// </summary>
        public static string PlaylistFavorites {
            get {
                return ResourceManager.GetString("PlaylistFavorites", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnMin.
        /// </summary>
        public static string BtnMin {
            get {
                return ResourceManager.GetString("BtnMin", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnMax.
        /// </summary>
        public static string BtnMax {
            get {
                return ResourceManager.GetString("BtnMax", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnBackToLibrary.
        /// </summary>
        public static string BtnBackToLibrary {
            get {
                return ResourceManager.GetString("BtnBackToLibrary", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnEditLoop.
        /// </summary>
        public static string BtnEditLoop {
            get {
                return ResourceManager.GetString("BtnEditLoop", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HeaderQueue.
        /// </summary>
        public static string HeaderQueue {
            get {
                return ResourceManager.GetString("HeaderQueue", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnFullScreen.
        /// </summary>
        public static string BtnFullScreen {
            get {
                return ResourceManager.GetString("BtnFullScreen", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PlaylistStatsFormat.
        /// </summary>
        public static string PlaylistStatsFormat {
            get {
                return ResourceManager.GetString("PlaylistStatsFormat", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to SearchPlaceholder.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to SearchInPlaceholder.
        /// </summary>
        public static string SearchInPlaceholder {
            get {
                return ResourceManager.GetString("SearchInPlaceholder", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusAnalyzing.
        /// </summary>
        public static string StatusAnalyzing {
            get {
                return ResourceManager.GetString("StatusAnalyzing", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusAnalyzeDone.
        /// </summary>
        public static string StatusAnalyzeDone {
            get {
                return ResourceManager.GetString("StatusAnalyzeDone", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusAnalyzeError.
        /// </summary>
        public static string StatusAnalyzeError {
            get {
                return ResourceManager.GetString("StatusAnalyzeError", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusPreparing.
        /// </summary>
        public static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuPlay.
        /// </summary>
        public static string MenuPlay {
            get {
                return ResourceManager.GetString("MenuPlay", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuPlaySelected.
        /// </summary>
        public static string MenuPlaySelected {
            get {
                return ResourceManager.GetString("MenuPlaySelected", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuAnalyze.
        /// </summary>
        public static string MenuAnalyze {
            get {
                return ResourceManager.GetString("MenuAnalyze", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuShowExplorer.
        /// </summary>
        public static string MenuShowExplorer {
            get {
                return ResourceManager.GetString("MenuShowExplorer", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuAddToPlaylist.
        /// </summary>
        public static string MenuAddToPlaylist {
            get {
                return ResourceManager.GetString("MenuAddToPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuRemove.
        /// </summary>
        public static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuDelete.
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgConfirmDelete.
        /// </summary>
        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgConfirmRemove.
        /// </summary>
        public static string MsgConfirmRemove {
            get {
                return ResourceManager.GetString("MsgConfirmRemove", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipCustomPlaylistOnly.
        /// </summary>
        public static string TipCustomPlaylistOnly {
            get {
                return ResourceManager.GetString("TipCustomPlaylistOnly", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipFindLoop.
        /// </summary>
        public static string TipFindLoop {
            get {
                return ResourceManager.GetString("TipFindLoop", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipEditProperties.
        /// </summary>
        public static string TipEditProperties {
            get {
                return ResourceManager.GetString("TipEditProperties", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DialogRenamePlaylist.
        /// </summary>
        public static string DialogRenamePlaylist {
            get {
                return ResourceManager.GetString("DialogRenamePlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DialogNewPlaylist.
        /// </summary>
        public static string DialogNewPlaylist {
            get {
                return ResourceManager.GetString("DialogNewPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PromptNewName.
        /// </summary>
        public static string PromptNewName {
            get {
                return ResourceManager.GetString("PromptNewName", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PromptPlaylistName.
        /// </summary>
        public static string PromptPlaylistName {
            get {
                return ResourceManager.GetString("PromptPlaylistName", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DefaultPlaylistName.
        /// </summary>
        public static string DefaultPlaylistName {
            get {
                return ResourceManager.GetString("DefaultPlaylistName", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgPlaylistExists.
        /// </summary>
        public static string MsgPlaylistExists {
            get {
                return ResourceManager.GetString("MsgPlaylistExists", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgConfirmDeletePlaylist.
        /// </summary>
        public static string MsgConfirmDeletePlaylist {
            get {
                return ResourceManager.GetString("MsgConfirmDeletePlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuRenameAlias.
        /// </summary>
        public static string MenuRenameAlias {
            get {
                return ResourceManager.GetString("MenuRenameAlias", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DialogRenameAlias.
        /// </summary>
        public static string DialogRenameAlias {
            get {
                return ResourceManager.GetString("DialogRenameAlias", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgNameEmpty.
        /// </summary>
        public static string MsgNameEmpty {
            get {
                return ResourceManager.GetString("MsgNameEmpty", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipPlayModeSingle.
        /// </summary>
        public static string TipPlayModeSingle {
            get {
                return ResourceManager.GetString("TipPlayModeSingle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipPlayModeList.
        /// </summary>
        public static string TipPlayModeList {
            get {
                return ResourceManager.GetString("TipPlayModeList", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipPlayModeShuffle.
        /// </summary>
        public static string TipPlayModeShuffle {
            get {
                return ResourceManager.GetString("TipPlayModeShuffle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnOk.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnCancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnClose.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TipRateCurrent.
        /// </summary>
        public static string TipRateCurrent {
            get {
                return ResourceManager.GetString("TipRateCurrent", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TrayHeader.
        /// </summary>
        public static string TrayHeader {
            get {
                return ResourceManager.GetString("TrayHeader", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TraySub.
        /// </summary>
        public static string TraySub {
            get {
                return ResourceManager.GetString("TraySub", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TrayMinimizeToTray.
        /// </summary>
        public static string TrayMinimizeToTray {
            get {
                return ResourceManager.GetString("TrayMinimizeToTray", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to TrayCloseToTray.
        /// </summary>
        public static string TrayCloseToTray {
            get {
                return ResourceManager.GetString("TrayCloseToTray", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuShowMainWindow.
        /// </summary>
        public static string MenuShowMainWindow {
            get {
                return ResourceManager.GetString("MenuShowMainWindow", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuHideToTray.
        /// </summary>
        public static string MenuHideToTray {
            get {
                return ResourceManager.GetString("MenuHideToTray", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuExit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuPause.
        /// </summary>
        public static string MenuPause {
            get {
                return ResourceManager.GetString("MenuPause", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuNext.
        /// </summary>
        public static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MenuPrevious.
        /// </summary>
        public static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to DialogSelectPlaylist.
        /// </summary>
        public static string DialogSelectPlaylist {
            get {
                return ResourceManager.GetString("DialogSelectPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PromptNewPlaylist.
        /// </summary>
        public static string PromptNewPlaylist {
            get {
                return ResourceManager.GetString("PromptNewPlaylist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to PromptEnterNameToCreate.
        /// </summary>
        public static string PromptEnterNameToCreate {
            get {
                return ResourceManager.GetString("PromptEnterNameToCreate", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to BtnAdd.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgAddSingleTrackTo.
        /// </summary>
        public static string MsgAddSingleTrackTo {
            get {
                return ResourceManager.GetString("MsgAddSingleTrackTo", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to MsgAddMultipleTracksTo.
        /// </summary>
        public static string MsgAddMultipleTracksTo {
            get {
                return ResourceManager.GetString("MsgAddMultipleTracksTo", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusAddedSingleTo.
        /// </summary>
        public static string StatusAddedSingleTo {
            get {
                return ResourceManager.GetString("StatusAddedSingleTo", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to StatusAddedMultipleTo.
        /// </summary>
        public static string StatusAddedMultipleTo {
            get {
                return ResourceManager.GetString("StatusAddedMultipleTo", resourceCulture);
            }
        }    }
}
