//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace seamless_loop_music.Statics {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("seamless_loop_music.Statics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply &amp; Test 的本地化字符串。
        /// </summary>
        public static string ApplyAndTest {
            get {
                return ResourceManager.GetString("ApplyAndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless Loop Music Player 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Folder 的本地化字符串。
        /// </summary>
        public static string BtnAddFolder {
            get {
                return ResourceManager.GetString("BtnAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to Library 的本地化字符串。
        /// </summary>
        public static string BtnBackToLibrary {
            get {
                return ResourceManager.GetString("BtnBackToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔄 Edit Loop 的本地化字符串。
        /// </summary>
        public static string BtnEditLoop {
            get {
                return ResourceManager.GetString("BtnEditLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✨ Immersive 的本地化字符串。
        /// </summary>
        public static string BtnFullScreen {
            get {
                return ResourceManager.GetString("BtnFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        public static string BtnMax {
            get {
                return ResourceManager.GetString("BtnMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        public static string BtnMin {
            get {
                return ResourceManager.GetString("BtnMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Now 的本地化字符串。
        /// </summary>
        public static string BtnNow {
            get {
                return ResourceManager.GetString("BtnNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Now 的本地化字符串。
        /// </summary>
        public static string BtnScan {
            get {
                return ResourceManager.GetString("BtnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning... 的本地化字符串。
        /// </summary>
        public static string BtnScanning {
            get {
                return ResourceManager.GetString("BtnScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync from Old Database 的本地化字符串。
        /// </summary>
        public static string BtnSync {
            get {
                return ResourceManager.GetString("BtnSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing... 的本地化字符串。
        /// </summary>
        public static string BtnSyncing {
            get {
                return ResourceManager.GetString("BtnSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update List 的本地化字符串。
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Management 的本地化字符串。
        /// </summary>
        public static string DataManagementHeader {
            get {
                return ResourceManager.GetString("DataManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync loop points and playlists from an older LoopData.db file 的本地化字符串。
        /// </summary>
        public static string DataManagementSub {
            get {
                return ResourceManager.GetString("DataManagementSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Playlist 的本地化字符串。
        /// </summary>
        public static string DefaultPlaylistName {
            get {
                return ResourceManager.GetString("DefaultPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Playlist 的本地化字符串。
        /// </summary>
        public static string DialogNewPlaylist {
            get {
                return ResourceManager.GetString("DialogNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Alias 的本地化字符串。
        /// </summary>
        public static string DialogRenameAlias {
            get {
                return ResourceManager.GetString("DialogRenameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Playlist 的本地化字符串。
        /// </summary>
        public static string DialogRenamePlaylist {
            get {
                return ResourceManager.GetString("DialogRenamePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Playlist 的本地化字符串。
        /// </summary>
        public static string DialogSelectPlaylist {
            get {
                return ResourceManager.GetString("DialogSelectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seamless Loop 的本地化字符串。
        /// </summary>
        public static string FeatureLoop {
            get {
                return ResourceManager.GetString("FeatureLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle between Partial Loop or Full Song Loop. 的本地化字符串。
        /// </summary>
        public static string FeatureLoopToolTip {
            get {
                return ResourceManager.GetString("FeatureLoopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path: 的本地化字符串。
        /// </summary>
        public static string FilePathTitle {
            get {
                return ResourceManager.GetString("FilePathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        public static string HeaderDuration {
            get {
                return ResourceManager.GetString("HeaderDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string HeaderEnd {
            get {
                return ResourceManager.GetString("HeaderEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note Dist. 的本地化字符串。
        /// </summary>
        public static string HeaderNoteDistance {
            get {
                return ResourceManager.GetString("HeaderNoteDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback Queue 的本地化字符串。
        /// </summary>
        public static string HeaderQueue {
            get {
                return ResourceManager.GetString("HeaderQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score 的本地化字符串。
        /// </summary>
        public static string HeaderScore {
            get {
                return ResourceManager.GetString("HeaderScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string HeaderStart {
            get {
                return ResourceManager.GetString("HeaderStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the interface display language 的本地化字符串。
        /// </summary>
        public static string LanguageSub {
            get {
                return ResourceManager.GetString("LanguageSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop End 的本地化字符串。
        /// </summary>
        public static string LoopEndLabel {
            get {
                return ResourceManager.GetString("LoopEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop Start 的本地化字符串。
        /// </summary>
        public static string LoopStartLabel {
            get {
                return ResourceManager.GetString("LoopStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match End 的本地化字符串。
        /// </summary>
        public static string MatchEnd {
            get {
                return ResourceManager.GetString("MatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search forward for a matching end point. 的本地化字符串。
        /// </summary>
        public static string MatchEndToolTip {
            get {
                return ResourceManager.GetString("MatchEndToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Start 的本地化字符串。
        /// </summary>
        public static string MatchStart {
            get {
                return ResourceManager.GetString("MatchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search backward for a matching start point. 的本地化字符串。
        /// </summary>
        public static string MatchStartToolTip {
            get {
                return ResourceManager.GetString("MatchStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Window 的本地化字符串。
        /// </summary>
        public static string MatchWindowTitle {
            get {
                return ResourceManager.GetString("MatchWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ➕ Add to Playlist... 的本地化字符串。
        /// </summary>
        public static string MenuAddToPlaylist {
            get {
                return ResourceManager.GetString("MenuAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ♾️ Batch Analyze (PyMusicLooper) 的本地化字符串。
        /// </summary>
        public static string MenuAnalyze {
            get {
                return ResourceManager.GetString("MenuAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🗑 Delete from Disk 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string MenuDeletePlaylist {
            get {
                return ResourceManager.GetString("MenuDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide to Tray 的本地化字符串。
        /// </summary>
        public static string MenuHideToTray {
            get {
                return ResourceManager.GetString("MenuHideToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Playlist 的本地化字符串。
        /// </summary>
        public static string MenuNewPlaylist {
            get {
                return ResourceManager.GetString("MenuNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⏭ Next 的本地化字符串。
        /// </summary>
        public static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⏸ Pause 的本地化字符串。
        /// </summary>
        public static string MenuPause {
            get {
                return ResourceManager.GetString("MenuPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▶ Play 的本地化字符串。
        /// </summary>
        public static string MenuPlay {
            get {
                return ResourceManager.GetString("MenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▶ Play Selected 的本地化字符串。
        /// </summary>
        public static string MenuPlaySelected {
            get {
                return ResourceManager.GetString("MenuPlaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⏮ Previous 的本地化字符串。
        /// </summary>
        public static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh List 的本地化字符串。
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ➖ Remove from List 的本地化字符串。
        /// </summary>
        public static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Alias 的本地化字符串。
        /// </summary>
        public static string MenuRenameAlias {
            get {
                return ResourceManager.GetString("MenuRenameAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 📁 Show in Explorer 的本地化字符串。
        /// </summary>
        public static string MenuShowExplorer {
            get {
                return ResourceManager.GetString("MenuShowExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Main Window 的本地化字符串。
        /// </summary>
        public static string MenuShowMainWindow {
            get {
                return ResourceManager.GetString("MenuShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} tracks to: 的本地化字符串。
        /// </summary>
        public static string MsgAddMultipleTracksTo {
            get {
                return ResourceManager.GetString("MsgAddMultipleTracksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 「{0}」 to: 的本地化字符串。
        /// </summary>
        public static string MsgAddSingleTrackTo {
            get {
                return ResourceManager.GetString("MsgAddSingleTrackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected {0} tracks from disk? They will be moved to the Recycle Bin. 的本地化字符串。
        /// </summary>
        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete playlist &apos;{0}&apos;? (&gt;﹏&lt;) 的本地化字符串。
        /// </summary>
        public static string MsgConfirmDeletePlaylist {
            get {
                return ResourceManager.GetString("MsgConfirmDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove the selected {0} tracks from playlist &quot;{1}&quot;? 的本地化字符串。
        /// </summary>
        public static string MsgConfirmRemove {
            get {
                return ResourceManager.GetString("MsgConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot be empty! 的本地化字符串。
        /// </summary>
        public static string MsgNameEmpty {
            get {
                return ResourceManager.GetString("MsgNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A playlist named &apos;{0}&apos; already exists! Try another name (´w｀) 的本地化字符串。
        /// </summary>
        public static string MsgPlaylistExists {
            get {
                return ResourceManager.GetString("MsgPlaylistExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan completed! 的本地化字符串。
        /// </summary>
        public static string MsgScanCompleted {
            get {
                return ResourceManager.GetString("MsgScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync completed successfully! 的本地化字符串。
        /// </summary>
        public static string MsgSyncSuccess {
            get {
                return ResourceManager.GetString("MsgSyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Folders 的本地化字符串。
        /// </summary>
        public static string MusicFoldersHeader {
            get {
                return ResourceManager.GetString("MusicFoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add folders containing your music files 的本地化字符串。
        /// </summary>
        public static string MusicFoldersSub {
            get {
                return ResourceManager.GetString("MusicFoldersSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlists 的本地化字符串。
        /// </summary>
        public static string MyPlaylist {
            get {
                return ResourceManager.GetString("MyPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Albums 的本地化字符串。
        /// </summary>
        public static string NavAlbum {
            get {
                return ResourceManager.GetString("NavAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Artists 的本地化字符串。
        /// </summary>
        public static string NavArtist {
            get {
                return ResourceManager.GetString("NavArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folders 的本地化字符串。
        /// </summary>
        public static string NavFolder {
            get {
                return ResourceManager.GetString("NavFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playlists 的本地化字符串。
        /// </summary>
        public static string NavPlaylist {
            get {
                return ResourceManager.GetString("NavPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Tracks 的本地化字符串。
        /// </summary>
        public static string PlaylistAll {
            get {
                return ResourceManager.GetString("PlaylistAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rating Playlist 的本地化字符串。
        /// </summary>
        public static string PlaylistFavorites {
            get {
                return ResourceManager.GetString("PlaylistFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} tracks 的本地化字符串。
        /// </summary>
        public static string PlaylistStatsFormat {
            get {
                return ResourceManager.GetString("PlaylistStatsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch playback mode (Single, List, Shuffle). 的本地化字符串。
        /// </summary>
        public static string PlayModeToolTip {
            get {
                return ResourceManager.GetString("PlayModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter name and press Enter to create 的本地化字符串。
        /// </summary>
        public static string PromptEnterNameToCreate {
            get {
                return ResourceManager.GetString("PromptEnterNameToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter new name: 的本地化字符串。
        /// </summary>
        public static string PromptNewName {
            get {
                return ResourceManager.GetString("PromptNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ＋ New Playlist 的本地化字符串。
        /// </summary>
        public static string PromptNewPlaylist {
            get {
                return ResourceManager.GetString("PromptNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter playlist name: 的本地化字符串。
        /// </summary>
        public static string PromptPlaylistName {
            get {
                return ResourceManager.GetString("PromptPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a candidate to preview or apply: 的本地化字符串。
        /// </summary>
        public static string PromptSelectLoop {
            get {
                return ResourceManager.GetString("PromptSelectLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Analyze 的本地化字符串。
        /// </summary>
        public static string PyRanking {
            get {
                return ResourceManager.GetString("PyRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use PyMusicLooper to find best loop points automatically. 的本地化字符串。
        /// </summary>
        public static string PyRankingToolTip {
            get {
                return ResourceManager.GetString("PyRankingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset AB 的本地化字符串。
        /// </summary>
        public static string ResetAB {
            get {
                return ResourceManager.GetString("ResetAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset loop points to the A/B seam point. 的本地化字符串。
        /// </summary>
        public static string ResetABToolTip {
            get {
                return ResourceManager.GetString("ResetABToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in {0}... 的本地化字符串。
        /// </summary>
        public static string SearchInPlaceholder {
            get {
                return ResourceManager.GetString("SearchInPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in library... 的本地化字符串。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Radius 的本地化字符串。
        /// </summary>
        public static string SearchRadiusTitle {
            get {
                return ResourceManager.GetString("SearchRadiusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added {0} tracks to 「{1}」 的本地化字符串。
        /// </summary>
        public static string StatusAddedMultipleTo {
            get {
                return ResourceManager.GetString("StatusAddedMultipleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added 「{0}」 to 「{1}」 的本地化字符串。
        /// </summary>
        public static string StatusAddedSingleTo {
            get {
                return ResourceManager.GetString("StatusAddedSingleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis done! Processed {0} tracks. 的本地化字符串。
        /// </summary>
        public static string StatusAnalyzeDone {
            get {
                return ResourceManager.GetString("StatusAnalyzeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis error: {0} 的本地化字符串。
        /// </summary>
        public static string StatusAnalyzeError {
            get {
                return ResourceManager.GetString("StatusAnalyzeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyzing ({0}/{1}): {2} 的本地化字符串。
        /// </summary>
        public static string StatusAnalyzing {
            get {
                return ResourceManager.GetString("StatusAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing... 的本地化字符串。
        /// </summary>
        public static string StatusPreparing {
            get {
                return ResourceManager.GetString("StatusPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removal is only possible in custom playlists. 的本地化字符串。
        /// </summary>
        public static string TipCustomPlaylistOnly {
            get {
                return ResourceManager.GetString("TipCustomPlaylistOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit properties 的本地化字符串。
        /// </summary>
        public static string TipEditProperties {
            get {
                return ResourceManager.GetString("TipEditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find loop points (PyMusicLooper) 的本地化字符串。
        /// </summary>
        public static string TipFindLoop {
            get {
                return ResourceManager.GetString("TipFindLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List Loop 的本地化字符串。
        /// </summary>
        public static string TipPlayModeList {
            get {
                return ResourceManager.GetString("TipPlayModeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shuffle 的本地化字符串。
        /// </summary>
        public static string TipPlayModeShuffle {
            get {
                return ResourceManager.GetString("TipPlayModeShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Loop 的本地化字符串。
        /// </summary>
        public static string TipPlayModeSingle {
            get {
                return ResourceManager.GetString("TipPlayModeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate Current Track (0-5) 的本地化字符串。
        /// </summary>
        public static string TipRateCurrent {
            get {
                return ResourceManager.GetString("TipRateCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop Candidates 的本地化字符串。
        /// </summary>
        public static string TitleLoopCandidates {
            get {
                return ResourceManager.GetString("TitleLoopCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Playlist 的本地化字符串。
        /// </summary>
        public static string ToolTipAddPlaylist {
            get {
                return ResourceManager.GetString("ToolTipAddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close to Tray 的本地化字符串。
        /// </summary>
        public static string TrayCloseToTray {
            get {
                return ResourceManager.GetString("TrayCloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tray Behavior 的本地化字符串。
        /// </summary>
        public static string TrayHeader {
            get {
                return ResourceManager.GetString("TrayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to Tray 的本地化字符串。
        /// </summary>
        public static string TrayMinimizeToTray {
            get {
                return ResourceManager.GetString("TrayMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure window behavior when minimizing or closing. 的本地化字符串。
        /// </summary>
        public static string TraySub {
            get {
                return ResourceManager.GetString("TraySub", resourceCulture);
            }
        }
    }
}
